config/routes.rb
Bimotaweb::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'

  namespace :me do
    root to: 'users#show'

    resource :user do
      member do
        get :profile
        post :commit_user_information
      end
    end
    resources :orders
    resources :vehicles do
      resources :orders, controller: 'vehicle_orders'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :orders
    end
  end

  namespace :admin do
    root to: 'orders#index'

    resources :users do
      member do
       post :commit_user_information
      end
      collection do
        get :check_existing_rut
      end
    end
    resources :orders
    resources :consumable_supplies do
      collection do
        get :add_units_modal
      end
      member do
        post :add_units
      end
    end
    resources :part_supplies do
      collection do
        get :add_units_modal
      end
      member do
        post :add_units
      end
    end
    resources :vehicles do
      resources :orders, controller: 'vehicle_orders' do
        member do
          post :add_comment, :start, :finish, :commit_new_task, :commit_supply, :commit_remove_supply, :commit_labor_cost
          get :add_consumable_supply, :remove_consumable_supply, :remove_part_supply, :get_consumed_supplies, :get_supply_stock, :add_part_supply, :labor_cost_form, :finish_task, :task_details, :pending_task
          delete :delete_task, :delete_comment
        end
      end
      member do
        get :assign_to_user, :find_users, :fetch_selected_user, :dissociate_user
        post :assign, :create_and_assign_user
      end
    end
    resources :bike_brands
    resource :setting do
      member do
        patch :commit_changes
      end
    end
  end

end

app/models/vehicle.rb
# -*- encoding : utf-8 -*-
class Vehicle < ActiveRecord::Base

  #relations
  belongs_to :user
  belongs_to :bike_brand
  has_many :orders

  #accessors
  # attr_accessible :brand, :model, :year, :license_plate, :chassis_number, :kilometraje

  #business methods

  def full_name
    "#{bike_brand.name} #{model}"
  end
end

app/controllers/admin/vehicles_controller.rb
# -*- encoding : utf-8 -*-
class Admin::VehiclesController < Admin::BaseController

  before_filter :load_vehicle, except: [:index, :new, :create]

  def index
    @page_title = 'Vehículos'
    if params[:owner_id].present?
      @vehicles = BikeVehicle.where(user_id: params[:owner_id]).order('created_at DESC').page params[:page]
    elsif params[:query]
      # This complex query should get the results by name no mather what spanish character was entered.
      conditions = ["( REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(vehicles.model),'á', 'a'),'é', 'e'),'í', 'i'),'ó', 'o'),'ú', 'u'),'ñ', 'n')  LIKE ? OR LOWER(vehicles.license_plate) LIKE ? OR LOWER(vehicles.chassis_number) LIKE ? OR LOWER(bike_brands.name) LIKE ? )", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%"]

      @vehicles = BikeVehicle.joins(:bike_brand).where(conditions).page params[:page]
    else
      @vehicles = BikeVehicle.order('created_at DESC').page params[:page]
    end
  end

  def new
    @page_title = 'Nuevo Vehículo'
    @vehicle = BikeVehicle.new
  end

  def create
    @vehicle = BikeVehicle.new(vehicle_params)
    if @vehicle.save
      flash[:success] = 'Vehículo guardado con éxito!'
      redirect_to assign_to_user_admin_vehicle_path(@vehicle)
    end
  end

  def assign_to_user
    @page_title = 'Asigna el vehículo a un usuario.'
    @new_user = User.new
  end

  def find_users
    conditions = ["REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(users.name),'á', 'a'),'é', 'e'),'í', 'i'),'ó', 'o'),'ú', 'u'),'ñ', 'n')  LIKE ? OR LOWER(users.email) LIKE ?", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%"]
    @users = User.where(conditions)
  end

  def fetch_selected_user
    @user = User.includes(:user_information).find(params[:user_id])
  end

  def assign
    if @vehicle.update!(vehicle_params)
      flash[:success] = 'El vehículo fue asignado con éxito.'
      redirect_to admin_vehicles_path and return
    else
      flash[:error] = 'Ocurrió un problema guardando los datos. Por favor inténtalo de nuevo.'
      redirect_to assign_to_user_admin_vehicle_path(@vehicle)
    end
  end

  def dissociate_user
    @vehicle.dissociate
    flash[:success] = 'El usuario y el vehículo fueron desvinculados.'
    redirect_to admin_vehicles_path
  end

  def create_and_assign_user
    params[:user][:password] = 'cambiame'
    params[:user][:password_confirmation] = 'cambiame'
    @user = User.new(user_params)

    if @user.save
      @user.reload
      @vehicle.user = @user
      @vehicle.save

      flash[:success] = 'El usuario fue creado y asignado al vehículo.'
      redirect_to admin_vehicles_path and return
    else
      flash[:error] = 'Ocurrió un error al guardar el usuario'
      redirect_to assign_to_user_admin_vehicle_path(@vehicle)
    end
  end

  def show
    @page_title = @vehicle.full_name
    @vehicle = BikeVehicle.find(params[:id])
    @orders = Order.where(vehicle_id: @vehicle.id)
    @user = @vehicle.user
  end

  def destroy
    @vehicle.destroy

    flash[:info] = 'El vehículo fue eliminado.'
    redirect_to vehicles_path
  end

  def edit

  end

  def update
    if @vehicle.update!(vehicle_params)
      flash[:success] = 'Se modificó correctamente la motocicleta'
      redirect_to admin_vehicle_path(@vehicle)
    end
  end

  private

  def vehicle_params
    params.require(:bike_vehicle).permit(:bike_brand_id, :model, :year, :license_plate, :chassis_number, :kilometraje, :user_id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def load_vehicle
    @vehicle = BikeVehicle.find(params[:id])
  end

end

app/controllers/me/orders_controller.rb
# -*- encoding : utf-8 -*-
class Me::OrdersController < ApplicationController

  def index
    @orders = current_user.orders
  end

  def show
    @order = current_user.orders.find(params[:id])
  end

end

app/controllers/me/users_controller.rb
# -*- encoding : utf-8 -*-
class Me::UsersController < ApplicationController

  def show #me page
    @page_id = 'me'
    if current_user.user_information.blank?
      @user_information = current_user.build_user_information
    end
  end

  def commit_user_information
    @user_information = current_user.build_user_information(user_information_params)
    @user_information.name = current_user.name
    if @user_information.save
      flash[:success] = 'Se guardaron tus datos con éxito!'
      redirect_to me_root_path
    end
  end

  def profile
    @user_information = current_user.user_information || current_user.build_user_information
  end

  private

  def user_information_params
    params.require(:user_information).permit(:name,:rut,:contact_phone,:address, :user_id)
  end

end

app/controllers/me/vehicle_orders_controller.rb
# -*- encoding : utf-8 -*-
class Me::VehicleOrdersController < ApplicationController
  before_filter :load_vehicle
  before_filter :load_order, only: :show

  def index
    @page_title = "Ordenes para tu #{@vehicle.full_name}"
    @orders = @vehicle.orders.page params[:page]
  end

  def show
    @page_title = "Orden ##{@order.uuid}"

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'orden_willy',
               :template => 'me/vehicle_orders/show.pdf.erb'
      end
    end
  end

  private

  def load_vehicle
    @vehicle = current_user.bike_vehicles.find(params[:vehicle_id])
  end

  def load_order
    @order = @vehicle.orders.find(params[:id])
  end

end

app/controllers/me/vehicles_controller.rb
# -*- encoding : utf-8 -*-
class Me::VehiclesController < ApplicationController

  def index
    @vehicles = current_user.bike_vehicles.includes(:bike_brand)
  end

  def edit
    @vehicle = current_user.bike_vehicles.find(params[:id])
    @page_title = "Editando #{@vehicle.full_name}"
  end

  def update
    @vehicle = current_user.bike_vehicles.find(params[:id])

    if @vehicle.update!(bike_params)
      flash[:success] = 'Se modificó correctamente el vehículo.'
      redirect_to me_vehicles_path
    else
      flash[:error] = 'Ocurrio un error actualizando el registro, por favor intentalo de nuevo.'
      render :edit
    end
  end

  def new
    @page_title = 'Nueva Moto'
    @vehicle = current_user.bike_vehicles.new
  end

  def create
    @vehicle = current_user.bike_vehicles.new(bike_params)
    if @vehicle.save
      flash[:success] = 'Tu moto fue agregada con éxito'
      redirect_to me_vehicles_path
    else
      render :new
    end
  end

  def destroy
    @vehicle = current_user.bike_vehicles.find(params[:id])

    if @vehicle.destroy
      flash[:success] = 'La moto fue eliminada.'
    else
      flash[:error] = 'No pudimos eliminar la moto seleccionada, inténtalo nuevamente.'
    end

    redirect_to me_vehicles_path
  end

  private

  def bike_params
    params.require(:bike_vehicle).permit(:bike_brand_id, :model, :year, :license_plate, :chassis_number, :kilometraje)
  end

end

app/controllers/vehicles_controller.rb
# -*- encoding : utf-8 -*-
class VehiclesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @page_title = 'Vehículos'
    @vehicles = Vehicle.order('created_at DESC').page params[:page]
  end

  def new
    if params[:client]
      @client = Client.find params[:client]
    end
    @page_title = 'Nuevo Vehículo'
    @vehicle = Vehicle.new
  end

  def create
    if params[:type] == 'auto'
      @vehicle = CarVehicle.new(params[:vehicle])
    else
      @vehicle = BikeVehicle.new(params[:vehicle])
    end

    unless params[:client].blank?
      @vehicle.client = Client.find params[:client]
    end

    if @vehicle.save
      flash[:success] = 'Vehículo guardado con éxito!'
      redirect_to vehicle_path(@vehicle)
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])
    @page_title = @vehicle.full_name
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    flash[:info] = 'El vehículo fue eliminado.'
    redirect_to vehicles_path
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.is_a?(BikeVehicle)
      redirect_to edit_bike_vehicle_path(@vehicle)
    else
      redirect_to edit_car_vehicle_path(@vehicle)
    end
  end

end

app/views/me/vehicles/_form.html.erb
 <fieldset>

    <% if @vehicle.errors.any? %>
      <div class="col-md-12 alert alert-danger">
        <a class="close" data-dismiss="alert" href="#">×</a>

        <p>Hay <%= pluralize(@vehicle.errors.count, 'error', 'errores') %>
          :
        </p>
        <ul>
          <% @vehicle.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :brand, 'Marca', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.select :bike_brand_id, options_for_select(BikeBrand.all.map{|brand| [brand.name, brand.id]}, @vehicle.bike_brand_id), {include_blank: 'Selecciona'}, {class: 'select2-drop col-md-12', required: 'required'} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :model, 'Modelo', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :model, class: 'form-control', required: 'required' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :year, 'Año', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :year, type: 'number', min: '1900', class: 'form-control', required: 'required' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :license_plate, 'Patente', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :license_plate, placeholder: 'AA000', class: 'form-control', required: 'required' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :chassis_number, 'Número de chasis', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :chassis_number, class: 'form-control', required: 'required' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :kilometraje, 'Kilometraje', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :kilometraje, type: 'number', min: '0', class: 'form-control', required: 'required' %>
      </div>
    </div>
  </fieldset>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-4">
      <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
    </div>
  </div>

app/views/me/vehicles/edit.html.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to '<i class="fa fa-chevron-left"></i> Volver'.html_safe, me_vehicles_path, :class => 'btn btn-default btn-lg pull-right' %>
      <h2><%= @page_title %></h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form_for @vehicle, url: me_vehicle_path(@vehicle), html: {class: 'form-horizontal'} do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

app/views/me/vehicles/index.html.erb
<div class="row">
  <div class="col-md-12">
    <%= link_to 'Ingresa una Moto', new_me_vehicle_path, :class => 'btn btn-primary pull-right' %>
    <h2>Mis Motos</h2>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @vehicles.any? %>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Año</th>
          <th>Patente</th>
          <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        <% @vehicles.each do |vehicle| %>
          <tr>
            <td><%= vehicle.bike_brand.name.titleize %></td>
            <td><%= vehicle.model %></td>
            <td><%= vehicle.year %></td>
            <td><%= vehicle.license_plate %></td>
            <td>
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" id="drop-vehicle-actions" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                  <i class="fa fa-cog"></i>
                  <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  <li><%= link_to '<i class="fa fa-pencil"></i> Editar'.html_safe, edit_me_vehicle_path(vehicle) %></li>
                  <li><%= link_to '<i class="fa fa-trash"></i> Eliminar'.html_safe, me_vehicle_path(vehicle), method: :delete, data: {confirm: '¿Estás seguro de que quieres eliminar este vehículo?'} %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to '<i class="fa fa-history"></i> Historial'.html_safe, me_vehicle_orders_path(vehicle) %></li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <h3>Aún no has ingresado tu(s) Moto(s)</h3>
      <h4>Ingresa tu primera moto <%= link_to 'Acá', new_me_vehicle_path %></h4>
    <% end %>
  </div>
</div>

app/views/me/vehicles/new.html.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to '<i class="fa fa-chevron-left"></i> Volver'.html_safe, me_vehicles_path, :class => 'btn btn-default btn-lg pull-right' %>
      <h2><%= @page_title %></h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form_for @vehicle, url: me_vehicles_path, html: {class: 'form-horizontal'} do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>