config/routes.rb
Bimotaweb::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'

  namespace :me do
    root to: 'users#show'

    resource :user do
      member do
        get :profile
        post :commit_user_information
      end
    end
    resources :orders
    resources :vehicles do
      resources :orders, controller: 'vehicle_orders'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :orders
    end
  end

  namespace :admin do
    root to: 'orders#index'

    resources :users do
      member do
       post :commit_user_information
      end
      collection do
        get :check_existing_rut
      end
    end
    resources :orders
    resources :consumable_supplies do
      collection do
        get :add_units_modal
      end
      member do
        post :add_units
      end
    end
    resources :part_supplies do
      collection do
        get :add_units_modal
      end
      member do
        post :add_units
      end
    end
    resources :vehicles do
      resources :orders, controller: 'vehicle_orders' do
        member do
          post :add_comment, :start, :finish, :commit_new_task, :commit_supply, :commit_remove_supply, :commit_labor_cost
          get :add_consumable_supply, :remove_consumable_supply, :remove_part_supply, :get_consumed_supplies, :get_supply_stock, :add_part_supply, :labor_cost_form, :finish_task, :task_details, :pending_task
          delete :delete_task, :delete_comment
        end
      end
      member do
        get :assign_to_user, :find_users, :fetch_selected_user, :dissociate_user
        post :assign, :create_and_assign_user
      end
    end
    resources :bike_brands
    resource :setting do
      member do
        patch :commit_changes
      end
    end
  end

end

app/models/part_supply.rb
# -*- encoding : utf-8 -*-
class PartSupply < Supply

  #relations


  #methods


end

app/controllers/admin/part_supplies_controller.rb
# -*- encoding : utf-8 -*-
class Admin::PartSuppliesController < Admin::BaseController

  def index
    @page_title = 'Repuestos'
    @part_supplies = PartSupply.page params[:page] #needs to have filters
  end

  def new
    @page_title = 'Nuevo Repuesto'
    @part = PartSupply.new
    @categories = SupplyCategory.part_categories
  end

  def create
    process_category

    @part = PartSupply.create(part_params)

    if @part.save
      flash[:success] = 'Repuesto creado'
      if params[:units].to_i > 0
        @part.add_units(params[:units].to_i)
      end
      redirect_to admin_part_supplies_path
    else
      flash[:error] = 'Ocurrio un error creando el repuesto, por favor intentalo de nuevo.'
      render :new
    end
  end

  def show
    @part = PartSupply.includes(:supply_items).find(params[:id])
    @page_title = @part.title.titleize
  end

  def edit
    @part = PartSupply.find params[:id]
    @page_title = @part.title.titleize
    @categories = SupplyCategory.part_categories
  end

  def update
    @part = PartSupply.find params[:id]

    process_category

    if @part.update!(part_params)
      flash[:success] = 'Se modificó correctamente el repuesto'
      redirect_to admin_part_supplies_path
    else
      flash[:error] = 'Ocurrio un error actualizando el registro, por favor intentalo de nuevo.'
      render :edit
    end
  end

  def destroy
    @part = PartSupply.find params[:id]
    if @part.destroy
      flash[:success] = 'Se eliminó el repuesto.'
    else
      flash[:error] = 'Ocurrió un error eliminando el repuesto.'
    end
    redirect_to admin_part_supplies_path
  end

  #Add units to stock
  def add_units_modal
    @supply = PartSupply.find(params[:supply_id])
  end

  def add_units
    @part = PartSupply.find params[:id]
    if @part.add_units(params[:units])
      flash[:success] = "Se agregaron #{params[:units]} unidades a #{@part.title.titleize}"
    else
      flash[:error] = "No se pudieron agregar unidades a #{@part.title.titleize}"
    end

    redirect_to admin_part_supplies_path
  end

  private

  def part_params
    params.require(:part_supply).permit(:brand, :model, :price, :category, :critical_stock)
  end

  def process_category
    if params[:new_category]
      new_category = SupplyCategory.create(name: params[:new_category], supply_type: SupplyCategory::TYPE_PART)
      params[:part_supply][:category] = new_category.name
    end
  end
end

app/controllers/part_supplies_controller.rb
# -*- encoding : utf-8 -*-
class PartSuppliesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @page_title = 'Repuestos'
    @part_supplies = PartSupply.page params[:page] #needs to have filters
  end

  def new
    @page_title = 'Nuevo Repuesto'
    @part = PartSupply.new
    @categories = SupplyCategory.part_categories
  end

  def create
    @part = PartSupply.create(params[:part_supply])

    if params[:new_category]
      new_category = SupplyCategory.create(name: params[:new_category], supply_type: SupplyCategory::TYPE_PART)
      @part.category = new_category.name
    end

    if @part.save
      flash[:success] = 'Repuesto creado'
      if params[:units].to_i > 0
        @part.add_units(params[:units].to_i)
      end
      redirect_to part_supplies_path
    else
      flash[:error] = 'Ocurrio un error creando el repuesto, por favor intentalo de nuevo.'
      render :new
    end
  end

  def edit
    @part = PartSupply.find params[:id]
    @page_title = @part.title.titleize
  end

  def update
    @part = PartSupply.find prams[:id]
    if @part.update_attributes(params[:part_supply])
      flash[:success] = 'Se modificó correctamente el repuesto'
      redirect_to part_supplies_path
    else
      flash[:error] = 'Ocurrio un error actualizando el registro, por favor intentalo de nuevo.'
      render :edit
    end
  end

  def destroy
    @part = PartSupply.find params[:id]
    if @part.destroy
      flash[:success] = 'Se eliminó el repuesto.'
    else
      flash[:error] = 'Ocurrió un error eliminando el repuesto.'
    end
    redirect_to part_supplies_path
  end

  #Add units to stock
  def add_units
    @part = PartSupply.find params[:id]
    if @part.add_units(params[:units])
      flash[:success] = "Se agregaron #{params[:units]} unidades a #{@part.title.titleize}"
    else
      flash[:error] = "No se pudieron agregar unidades a #{@part.title.titleize}"
    end

    redirect_to part_supplies_path
  end
end

app/views/admin/part_supplies/_add_units_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="units-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Agregar stock a <%= @supply.title %></h4>
      </div>
      <%= form_tag add_units_admin_part_supply_path(@supply), :class => 'form-horizontal' do %>
        <div class="modal-body">
          <div class="form-group">
            <%= label_tag :units, 'Cantidad', class: 'col-md-2 control-label' %>
            <div class="col-md-6">
              <%= text_field_tag :units, 0, type: 'number', min: '1', class: 'form-control' %>
              <p class="help-block">Se agregará este numero de unidades al stock actual de <%= @supply.available_supplies_count %></p>
            </div>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
          <%= submit_tag 'Guardar', :class => 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/part_supplies/_form.erb
<fieldset>

  <% if @part.errors.any? %>
      <div class="col-md-12 alert alert-danger">
        <a class="close" data-dismiss="alert" href="#">×</a>

        <p>Hay <%= pluralize(@part.errors.count, 'error', 'errores') %>
          :
        </p>
        <ul>
          <% @part.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <div class="form-group">
    <%= f.label :brand, 'Marca', class: 'col-md-2 control-label' %>
    <div class="col-md-4">
      <%= f.text_field :brand, class: 'form-control', required: 'required', :oninvalid => "this.setCustomValidity('Ingresa la marca del repuesto.')", :onchange => "this.setCustomValidity('')" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :model, 'Modelo', class: 'col-md-2 control-label' %>
    <div class="col-md-4">
      <%= f.text_field :model, class: 'form-control', required: 'required', :oninvalid => "this.setCustomValidity('Ingresa el modelo del repuesto.')", :onchange => "this.setCustomValidity('')" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, 'Precio', class: 'col-md-2 control-label' %>
    <div class="col-md-4">
      <%= f.text_field :price, class: 'form-control', type: 'number', min: '0', required: 'required', :oninvalid => "this.setCustomValidity('Ingresa el valor (a cobrar) del repuesto.')", :onchange => "this.setCustomValidity('')" %>
    </div>
  </div>

  <% if @categories.any? %>
      <div class="form-group" id="category_select">
        <%= f.label :category, 'Categoría', class: 'col-md-2 control-label' %>
        <div class="col-md-4">
          <%= f.select :category, options_for_select(@categories.map { |cat| [cat.name, cat.name] }, @part.category), {include_blank: 'Selecciona'}, {class: 'select2-drop col-md-12'} %>
          <span class="help-block"><a id="new_cat">Agrega aquí una nueva categoría</a></span>
        </div>
      </div>

      <div class="form-group" id="new_category" style="display: none;">
        <%= label_tag :new_category, 'Nueva Categoría', class: 'col-md-2 control-label' %>
        <div class="col-md-4">
          <%= text_field_tag :new_category, '', class: 'form-control' %>
          <span class="help-block"><a id="back_to_select">Selecciona una categoría existente</a></span>
        </div>
      </div>
  <% else %>
      <div class="form-group">
        <%= label_tag :new_category, 'Nueva Categoría', class: 'col-md-2 control-label' %>
        <div class="col-md-4">
          <%= text_field_tag :new_category, '', class: 'form-control' %>
        </div>
      </div>
  <% end %>

  <% unless is_edit %>
      <div class="form-group">
        <%= label_tag :units, 'Stock inicial', class: 'col-md-2 control-label' %>
        <div class="col-md-4">
          <%= text_field_tag :units, 0, type: 'number', min: '0', class: 'form-control' %>
          <p class="help-block">Opcional.</p>
        </div>
      </div>
  <% end %>

  <div class="form-group">
    <%= f.label :critical_stock, 'Stock Crítico', class: 'col-md-2 control-label' %>
    <div class="col-md-4">
      <%= f.text_field :critical_stock, class: 'form-control', type: 'number', min: '0', required: 'required', :oninvalid => "this.setCustomValidity('Ingresa el stock crtítico.')", :onchange => "this.setCustomValidity('')" %>
      <p class="help-block">Se notificará cuando el stock llegue a este valor</p>
    </div>
  </div>

</fieldset>
<div class="form-group">
  <div class="col-md-offset-2 col-md-4">
    <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
  </div>
</div>

<script type="text/javascript">
  $('#new_cat').on('click', function () {
    $('#category_select').toggle();
    $('#new_category').toggle();
  });

  $('#back_to_select').on('click', function () {
    $('#category_select').toggle();
    $('#new_category').toggle();
  });
</script>

app/views/admin/part_supplies/add_units_modal.js.erb
$('#add-units-modal').html('<%= j render(partial: 'add_units_modal') %>');
$('#units-modal').modal('show');

app/views/admin/part_supplies/edit.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to '<i class="fa fa-chevron-left"></i> Volver'.html_safe, admin_part_supplies_path, :class => 'btn btn-default btn-lg pull-right' %>
      <h2><%= @page_title %></h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form_for @part, url: admin_part_supply_path(@part), html: {class: 'form-horizontal'} do |f| %>
        <%= render 'form', is_edit: true, f: f %>
    <% end %>
  </div>
</div>

app/views/admin/part_supplies/index.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to 'Ingresa un Repuesto!', new_admin_part_supply_path, :class => 'btn btn-primary btn-large pull-right' %>
      <h2><%= @page_title %></h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @part_supplies && @part_supplies.any? %>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Precio unitario</th>
          <th>Categoría</th>
          <th>Stock</th>
          <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        <% @part_supplies.each do |supply| %>
          <tr>
            <td><%= link_to supply.brand, admin_part_supply_path(supply) %></td>
            <td><%= supply.model %></td>
            <td><%= number_to_currency(supply.price, separator: ',', delimiter: '.', format: '%u %n') %></td>
            <td><%= supply.category %></td>
            <td><%= supply.available_supplies_count %></td>
            <td class="delete">
              <div class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-cog"></i>
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to '<i class="fa fa-plus"></i> Agregar unidades'.html_safe, '#', class: 'add-units', data: {supply_id: supply.id} %></li>
                  <li>
                    <a href="<%= edit_admin_part_supply_path(supply) %>"><i class="fa fa-edit"></i> Editar</a>
                  </li>
                  <li>
                    <%= link_to raw('<i class="fa fa-trash"></i> Eliminar'), admin_part_supply_path(supply), :method => 'delete', :confirm => '¿Estás seguro que deseas eliminar este repuesto?' if can? :manage, PartSupply %>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <h3>Aún no hay repuestos ingresados :(</h3>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="text-center">
      <%= paginate @part_supplies %>
    </div>
    <div class="pull-right">
      <%= page_entries_info(@part_supplies) if @part_supplies.any? %>
    </div>
  </div>
</div>

<div id="add-units-modal"></div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.add-units').on('click', function(){
      var supply_id = $(this).data('supply-id');
      var url = '<%= add_units_modal_admin_part_supplies_path(format: 'js') %>?supply_id='+ supply_id;
      $.getScript(url);
    });
  });
</script>

app/views/admin/part_supplies/new.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to '<i class="fa fa-chevron-left"></i> Volver'.html_safe, admin_part_supplies_path, :class => 'btn btn-default btn-lg pull-right' %>
      <h2><%= @page_title %></h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= form_for @part, url: admin_part_supplies_path, html: {class: 'form-horizontal'} do |f| %>
        <%= render 'form', is_edit: true, f: f %>
    <% end %>
  </div>
</div>

app/views/admin/part_supplies/show.html.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to '<i class="fa fa-chevron-left"></i> Volver'.html_safe, admin_part_supplies_path, :class => 'btn btn-default btn-lg pull-right' %>
      <h2><%= @page_title %></h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">

    <dl>
      <dt>Marca</dt>
      <dd><%= @part.brand %></dd>
      <dt>Modelo</dt>
      <dd><%= @part.model %></dd>
      <dt>Categoría</dt>
      <dd><%= @part.category %></dd>
      <dt>Precio</dt>
      <dd><%= money_for @part.price %></dd>
      <dt>Stock actual</dt>
      <dd><%= @part.supply_items.available.count %> <%= link_to '<i class="fa fa-plus"></i> Agregar unidades'.html_safe, '#', class: 'add-units', style: 'font-size: 10px;', data: {supply_id: @part.id} %></dd>
      <dt>Stock consumido</dt>
      <dd><%= @part.supply_items.unavailable.count %></dd>
    </dl>

  </div>
</div>


<div id="add-units-modal"></div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.add-units').on('click', function(){
      var supply_id = $(this).data('supply-id');
      var url = '<%= add_units_modal_admin_part_supplies_path(format: 'js') %>?supply_id='+ supply_id;
      $.getScript(url);
    });
  });
</script>