config/routes.rb
Bimotaweb::Application.routes.draw do
  devise_for :users

  root :to => 'home#index'

  namespace :me do
    root to: 'users#show'

    resource :user do
      member do
        get :profile
        post :commit_user_information
      end
    end
    resources :orders
    resources :vehicles do
      resources :orders, controller: 'vehicle_orders'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :orders
    end
  end

  namespace :admin do
    root to: 'orders#index'

    resources :users do
      member do
       post :commit_user_information
      end
      collection do
        get :check_existing_rut
      end
    end
    resources :orders
    resources :consumable_supplies do
      collection do
        get :add_units_modal
      end
      member do
        post :add_units
      end
    end
    resources :part_supplies do
      collection do
        get :add_units_modal
      end
      member do
        post :add_units
      end
    end
    resources :vehicles do
      resources :orders, controller: 'vehicle_orders' do
        member do
          post :add_comment, :start, :finish, :commit_new_task, :commit_supply, :commit_remove_supply, :commit_labor_cost
          get :add_consumable_supply, :remove_consumable_supply, :remove_part_supply, :get_consumed_supplies, :get_supply_stock, :add_part_supply, :labor_cost_form, :finish_task, :task_details, :pending_task
          delete :delete_task, :delete_comment
        end
      end
      member do
        get :assign_to_user, :find_users, :fetch_selected_user, :dissociate_user
        post :assign, :create_and_assign_user
      end
    end
    resources :bike_brands
    resource :setting do
      member do
        patch :commit_changes
      end
    end
  end

end

app/models/vehicle.rb
# -*- encoding : utf-8 -*-
class Vehicle < ActiveRecord::Base

  #relations
  belongs_to :user
  belongs_to :bike_brand
  has_many :orders

  #accessors
  # attr_accessible :brand, :model, :year, :license_plate, :chassis_number, :kilometraje

  #business methods

  def full_name
    "#{bike_brand.name} #{model}"
  end
end

app/controllers/admin/vehicles_controller.rb
# -*- encoding : utf-8 -*-
class Admin::VehiclesController < Admin::BaseController

  before_filter :load_vehicle, except: [:index, :new, :create]

  def index
    @page_title = 'Vehículos'
    if params[:owner_id].present?
      @vehicles = BikeVehicle.where(user_id: params[:owner_id]).order('created_at DESC').page params[:page]
    elsif params[:query]
      # This complex query should get the results by name no mather what spanish character was entered.
      conditions = ["( REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(vehicles.model),'á', 'a'),'é', 'e'),'í', 'i'),'ó', 'o'),'ú', 'u'),'ñ', 'n')  LIKE ? OR LOWER(vehicles.license_plate) LIKE ? OR LOWER(vehicles.chassis_number) LIKE ? OR LOWER(bike_brands.name) LIKE ? )", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%"]

      @vehicles = BikeVehicle.joins(:bike_brand).where(conditions).page params[:page]
    else
      @vehicles = BikeVehicle.order('created_at DESC').page params[:page]
    end
  end

  def new
    @page_title = 'Nuevo Vehículo'
    @vehicle = BikeVehicle.new
  end

  def create
    @vehicle = BikeVehicle.new(vehicle_params)
    if @vehicle.save
      flash[:success] = 'Vehículo guardado con éxito!'
      redirect_to assign_to_user_admin_vehicle_path(@vehicle)
    end
  end

  def assign_to_user
    @page_title = 'Asigna el vehículo a un usuario.'
    @new_user = User.new
  end

  def find_users
    conditions = ["REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(users.name),'á', 'a'),'é', 'e'),'í', 'i'),'ó', 'o'),'ú', 'u'),'ñ', 'n')  LIKE ? OR LOWER(users.email) LIKE ?", "%#{params[:query].downcase}%", "%#{params[:query].downcase}%"]
    @users = User.where(conditions)
  end

  def fetch_selected_user
    @user = User.includes(:user_information).find(params[:user_id])
  end

  def assign
    if @vehicle.update!(vehicle_params)
      flash[:success] = 'El vehículo fue asignado con éxito.'
      redirect_to admin_vehicles_path and return
    else
      flash[:error] = 'Ocurrió un problema guardando los datos. Por favor inténtalo de nuevo.'
      redirect_to assign_to_user_admin_vehicle_path(@vehicle)
    end
  end

  def dissociate_user
    @vehicle.dissociate
    flash[:success] = 'El usuario y el vehículo fueron desvinculados.'
    redirect_to admin_vehicles_path
  end

  def create_and_assign_user
    params[:user][:password] = 'cambiame'
    params[:user][:password_confirmation] = 'cambiame'
    @user = User.new(user_params)

    if @user.save
      @user.reload
      @vehicle.user = @user
      @vehicle.save

      flash[:success] = 'El usuario fue creado y asignado al vehículo.'
      redirect_to admin_vehicles_path and return
    else
      flash[:error] = 'Ocurrió un error al guardar el usuario'
      redirect_to assign_to_user_admin_vehicle_path(@vehicle)
    end
  end

  def show
    @page_title = @vehicle.full_name
    @vehicle = BikeVehicle.find(params[:id])
    @orders = Order.where(vehicle_id: @vehicle.id)
    @user = @vehicle.user
  end

  def destroy
    @vehicle.destroy

    flash[:info] = 'El vehículo fue eliminado.'
    redirect_to vehicles_path
  end

  def edit

  end

  def update
    if @vehicle.update!(vehicle_params)
      flash[:success] = 'Se modificó correctamente la motocicleta'
      redirect_to admin_vehicle_path(@vehicle)
    end
  end

  private

  def vehicle_params
    params.require(:bike_vehicle).permit(:bike_brand_id, :model, :year, :license_plate, :chassis_number, :kilometraje, :user_id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def load_vehicle
    @vehicle = BikeVehicle.find(params[:id])
  end

end

app/controllers/me/vehicles_controller.rb
# -*- encoding : utf-8 -*-
class Me::VehiclesController < ApplicationController

  def index
    @vehicles = current_user.bike_vehicles.includes(:bike_brand)
  end

  def edit
    @vehicle = current_user.bike_vehicles.find(params[:id])
    @page_title = "Editando #{@vehicle.full_name}"
  end

  def update
    @vehicle = current_user.bike_vehicles.find(params[:id])

    if @vehicle.update!(bike_params)
      flash[:success] = 'Se modificó correctamente el vehículo.'
      redirect_to me_vehicles_path
    else
      flash[:error] = 'Ocurrio un error actualizando el registro, por favor intentalo de nuevo.'
      render :edit
    end
  end

  def new
    @page_title = 'Nueva Moto'
    @vehicle = current_user.bike_vehicles.new
  end

  def create
    @vehicle = current_user.bike_vehicles.new(bike_params)
    if @vehicle.save
      flash[:success] = 'Tu moto fue agregada con éxito'
      redirect_to me_vehicles_path
    else
      render :new
    end
  end

  def destroy
    @vehicle = current_user.bike_vehicles.find(params[:id])

    if @vehicle.destroy
      flash[:success] = 'La moto fue eliminada.'
    else
      flash[:error] = 'No pudimos eliminar la moto seleccionada, inténtalo nuevamente.'
    end

    redirect_to me_vehicles_path
  end

  private

  def bike_params
    params.require(:bike_vehicle).permit(:bike_brand_id, :model, :year, :license_plate, :chassis_number, :kilometraje)
  end

end

app/controllers/vehicles_controller.rb
# -*- encoding : utf-8 -*-
class VehiclesController < ApplicationController
  before_filter :authenticate_user!

  def index
    @page_title = 'Vehículos'
    @vehicles = Vehicle.order('created_at DESC').page params[:page]
  end

  def new
    if params[:client]
      @client = Client.find params[:client]
    end
    @page_title = 'Nuevo Vehículo'
    @vehicle = Vehicle.new
  end

  def create
    if params[:type] == 'auto'
      @vehicle = CarVehicle.new(params[:vehicle])
    else
      @vehicle = BikeVehicle.new(params[:vehicle])
    end

    unless params[:client].blank?
      @vehicle.client = Client.find params[:client]
    end

    if @vehicle.save
      flash[:success] = 'Vehículo guardado con éxito!'
      redirect_to vehicle_path(@vehicle)
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])
    @page_title = @vehicle.full_name
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    flash[:info] = 'El vehículo fue eliminado.'
    redirect_to vehicles_path
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.is_a?(BikeVehicle)
      redirect_to edit_bike_vehicle_path(@vehicle)
    else
      redirect_to edit_car_vehicle_path(@vehicle)
    end
  end

end

app/views/admin/vehicles/_form.erb
<%= form_for @vehicle, url: admin_vehicles_path, html: {class: 'form-horizontal'} do |f| %>
  <fieldset>

    <% if @vehicle.errors.any? %>
      <div class="col-md-12 alert alert-danger">
        <a class="close" data-dismiss="alert" href="#">×</a>

        <p>Hay <%= pluralize(@vehicle.errors.count, 'error', 'errores') %>
          :
        </p>
        <ul>
          <% @vehicle.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :brand, 'Marca', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.select :bike_brand_id, options_for_select(BikeBrand.all.map{|brand| [brand.name, brand.id]}, @vehicle.bike_brand_id), {include_blank: 'Selecciona'}, {class: 'select2-drop col-md-12', required: 'required'} %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :model, 'Modelo', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :model, class: 'form-control', required: 'required' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :year, 'Año', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :year, type: 'number', min: '1900', class: 'form-control', required: 'required' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :license_plate, 'Patente', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :license_plate, placeholder: 'AA000', class: 'form-control', required: 'required' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :chassis_number, 'Número de chasis', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :chassis_number, class: 'form-control', required: 'required' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :kilometraje, 'Kilometraje', class: 'col-md-2 control-label' %>
      <div class="col-md-4">
        <%= f.text_field :kilometraje, type: 'number', min: '0', class: 'form-control', required: 'required' %>
      </div>
    </div>
  </fieldset>
  <div class="form-group">
    <div class="col-md-offset-2 col-md-4">
      <%= f.submit 'Guardar', :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/admin/vehicles/_selected_user.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <% if @user %>
      <h3>Información del usuario seleccionado</h3>
      <ul>
        <li>Nombre: <%= @user.name %></li>
        <li>Email: <%= @user.email %></li>
        <li>RUT: <%= format_rut_for(@user) %></li>
        <li>Nº de contacto: <%= @user.user_information ? @user.user_information.contact_phone : 'N/D' %></li>
        <li>Dirección: <%= @user.user_information ? @user.user_information.address : 'N/D' %></li>
      </ul>

      <%= form_tag assign_admin_vehicle_path(@vehicle) do %>
        <%= hidden_field_tag 'bike_vehicle[user_id]', @user.id %>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-4">
            <%= submit_tag 'Confirmar', :class => 'btn btn-primary', data: {disable_with: 'Confirmando...'} %>
          </div>
        </div>
      <% end %>
    <% else %>
      <h3>Inténtalo de nuevo.</h3>
    <% end %>
  </div>
</div>

app/views/admin/vehicles/_user_search_results.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <% if @users && @users.any? %>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Mail</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td class="center">
              <%= radio_button_tag(:user_id, user.id, false, class: 'user-radio') %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <h3>No se encontraron resultados</h3>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $('.user-radio').change(function () {
    if ($(this).is(':checked')) {
      var selected_user_id = $(this).val();
      var url = '<%= fetch_selected_user_admin_vehicle_path(@vehicle) %>?user_id=' + selected_user_id;
      $.getScript(url);
    }
  });
</script>

app/views/admin/vehicles/assign_to_user.html.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to '<i class="fa fa-chevron-left"></i> Volver'.html_safe, admin_orders_path, :class => 'btn btn-default btn-lg pull-right' %>
      <h2><%= @page_title %></h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <ul class="nav nav-tabs nav-justified">
      <li role="presentation" class="active">
        <a href="#existing" aria-controls="existing" role="tab" data-toggle="tab">Usuario Existente</a></li>
      <li role="presentation"><a href="#new" aria-controls="new" role="tab" data-toggle="tab">Nuevo Usuario</a></li>
    </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="existing">
        <div class="row">
          <div class="col-md-6">
            <div class="margin-b">
              <%= form_tag({:action => 'find_users'}, :method => 'get', remote: true) do %>
                <div class="input-group">
                  <%= text_field_tag 'query', '', :placeholder => 'Busca por Nombre o Email...', :class => 'form-control' %>
                  <span class="input-group-btn">
            <%= button_tag raw('<i class="fa fa-search"></i>'), :class => 'btn btn-default', :disable_with => '<i class="fa fa-search"></i>' %>
          </span>
                </div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div id="users-result"></div>
          </div>
          <div class="col-md-6">
            <div id="selected-user"></div>
          </div>
        </div>

      </div>
      <div role="tabpanel" class="tab-pane" id="new">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_for @new_user, url: create_and_assign_user_admin_vehicle_path(@vehicle), html: { class: 'form-horizontal' } do |f| %>

              <div class="form-group">
                <%= f.label :name, 'Nombre', class: 'col-md-2 control-label' %>
                <div class="col-md-4">
                  <%= f.text_field :name, class: 'form-control', required: 'required', :oninvalid => "this.setCustomValidity('Ingresa el nombre del usuario.')", :onchange => "this.setCustomValidity('')" %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :email, 'Email', class: 'col-md-2 control-label' %>
                <div class="col-md-4">
                  <%= f.email_field :email, class: 'form-control', required: 'required', :oninvalid => "this.setCustomValidity('Ingresa el email del usuario.')", :onchange => "this.setCustomValidity('')" %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-md-offset-2 col-md-4">
                  <%= f.submit 'Confirmar', :class => 'btn btn-primary' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/vehicles/edit.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to '<i class="fa fa-chevron-left"></i> Volver'.html_safe, admin_vehicle_path(@vehicle), :class => 'btn btn-default btn-lg pull-right' %>
      <h2><%= @page_title %></h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/vehicles/fetch_selected_user.js.erb
$('#selected-user').html('<%= j render(partial: 'selected_user') %>');

app/views/admin/vehicles/find_users.js.erb
$('#users-result').html('<%= j render(partial: 'user_search_results') %>');

app/views/admin/vehicles/index.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to 'Ingresa un Vehículo!', new_admin_vehicle_path, :class => 'btn btn-primary btn-large pull-right' %>
      <h2><%= @page_title %></h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="margin-b">
      <%= form_tag({:action => 'index'}, :method => 'get') do %>
        <div class="input-group">
          <%= text_field_tag 'query', '', :placeholder => 'Buscar...', :class => 'form-control' %>
          <span class="input-group-btn">
            <%= button_tag raw('<i class="fa fa-search"></i>'), :class => 'btn btn-default', :disable_with => '<i class="fa fa-search"></i>' %>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @vehicles && @vehicles.any? %>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Año</th>
          <th>Nombre Cliente</th>
          <th>Acciones</th>
        </tr>
        </thead>
        <tbody>
        <% @vehicles.each do |vehicle| %>
          <tr>
            <td><%= link_to vehicle.bike_brand.name, admin_vehicle_path(vehicle) %></td>
            <td><%= vehicle.model %></td>
            <td><%= vehicle.year %></td>
            <td><%= vehicle.user ? vehicle.user.name.titleize : "Sin Dueño (#{link_to 'asignar', assign_to_user_admin_vehicle_path(vehicle)})".html_safe %></td>
            <td class="delete">
              <div class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-cog"></i>
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to(raw('<i class="fa fa-file-text-o"></i> Ordenes'), admin_vehicle_orders_path(vehicle)) %>
                  </li>
                  <li>
                    <%= link_to '<i class="fa fa-edit"></i> Editar'.html_safe, edit_admin_vehicle_path(vehicle) %>
                  </li>
                  <li>
                    <%= link_to(raw('<i class="fa fa-user-times"></i> Desvincular'), dissociate_user_admin_vehicle_path(vehicle), data: {confirm: '¿Estás seguro que deseas desvincular el vehículo de este usuario?'}) if can? :manage, Vehicle %>
                  </li>
                  <li>
                    <%= link_to(raw('<i class="fa fa-trash"></i> Eliminar'), admin_vehicle_path(vehicle), :method => 'delete', data: {confirm: '¿Estás seguro que deseas eliminar este vehículo?'}) if can? :manage, Vehicle %>
                  </li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <h3>Aún no hay vehículos ingresados :(</h3>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="text-center">
      <%= paginate @vehicles %>
    </div>
    <div class="pull-right">
      <%= page_entries_info(@vehicles) if @vehicles.any? %>
    </div>
  </div>
</div>

app/views/admin/vehicles/new.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to '<i class="fa fa-chevron-left"></i> Volver'.html_safe, admin_vehicles_path, :class => 'btn btn-default btn-lg pull-right' %>
      <h2><%= @page_title %><%= " para #{@client.short_name}" if @client %></h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/vehicles/show.erb
<div class="row">
  <div class="col-md-12 actions">
    <div class="page-header">
      <%= link_to '<i class="fa fa-chevron-left"></i> Volver'.html_safe, admin_vehicles_path, :class => 'btn btn-default btn-lg pull-right' %>
      <%= link_to 'Crear Orden', new_admin_vehicle_order_path(@vehicle), :class => 'btn btn-default btn-lg pull-right' %>
      <h2><%= @page_title %><%= " para #{@client.short_name}" if @client %></h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <div class="well">
      <h3>Detalle</h3>
      <dl class="dl-vm">
        <dt>Marca</dt>
        <dd><%= @vehicle.bike_brand.name %></dd>

        <dt>Modelo</dt>
        <dd><%= @vehicle.model %></dd>

        <dt>Año</dt>
        <dd><%= @vehicle.year %></dd>

        <dt>Patente</dt>
        <dd><%= @vehicle.license_plate %></dd>

        <dt>Número de chasis</dt>
        <dd><%= @vehicle.chassis_number %></dd>

        <dt>Kilometraje</dt>
        <dd><%= @vehicle.kilometraje %></dd>
      </dl>
    </div>
  </div>

  <div class="col-md-8">
    <% if @orders && @orders.any? %>
      <h4>Lista ordenes vehìculo</h4>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>ID</th>
          <th>Cliente</th>
          <th>Estado</th>
        </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= link_to order.uuid, admin_vehicle_order_path(@vehicle, order) %></td>
            <td><%= order.user.name %></td>
            <td><%= status_for(order) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <h3>Aún no hay ordenes creadas :(</h3>
    <% end %>
  </div>

</div>
</div>